language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t mukil/react-app-dev:latest -f Dockerfile.dev .
script:
  - docker run -it mukil/react-app-dev npm run test -- --coverage